### ISSUE TITLE
feat: create a variety of badges

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/master-agile#32]
As a **User**,
I want to have badges of:

* [ ] feat: badge of different shapes and fills #33
* [ ] feat: badge of different sizes #34
* [ ] feat: badges of different colors #35

![image](https://user-images.githubusercontent.com/1318985/79637029-b704f900-8173-11ea-90e2-ed9e48ab968f.png)
