### ISSUE TITLE
feat: [marianzburlea] [all] badges of different colors

### ISSUE THREAD

**Issue by marianzburlea** [codetapacademy/master-agile#45]
# Requirements

As a **User**, I want to be able to see badges of different colors.

![image](https://user-images.githubusercontent.com/1318985/79637029-b704f900-8173-11ea-90e2-ed9e48ab968f.png)

* [x] feat: [marianzburlea] [html-css] badges of different colors #39
* [x] feat: [marianzburlea] [pug-sass] badges of different colors #40
* [x]  feat: [marianzburlea] [angular] badges of different colors #41
* [x] feat: [marianzburlea] [react] badges of different colors #42 
* [x] feat: [marianzburlea] [svelte] badges of different colors #43
* [x] feat: [marianzburlea] [vue] badges of different colors #44 

## Original from
feat: badges of different colors #35

**Comment by Nicolleta1981** [comment]
Yes yes I can see colors. At least those :))
